[package]
name = "adventofcode-rs"
version = "1.0.0"
authors = ["Phillip Schichtel <phillip@schich.tel>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
